// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGO3eK0c7vlWvC94mbgTY6l0QXCTUrFNA',
    appId: '1:1030067242876:web:9bfd0ff4cf0b91b13846f9',
    messagingSenderId: '1030067242876',
    projectId: 'ur-next-route',
    authDomain: 'ur-next-route.firebaseapp.com',
    storageBucket: 'ur-next-route.appspot.com',
    measurementId: 'G-PDRRYMT4QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGdBe32x_W9g1wm1sMJeT7slBti3ZGko',
    appId: '1:1030067242876:android:d1f73e3264c1b40d3846f9',
    messagingSenderId: '1030067242876',
    projectId: 'ur-next-route',
    storageBucket: 'ur-next-route.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZOUAYjum-bLfwKv1YWnGfhs5jKSiRM0',
    appId: '1:1030067242876:ios:ea66c9a1b0160f993846f9',
    messagingSenderId: '1030067242876',
    projectId: 'ur-next-route',
    storageBucket: 'ur-next-route.appspot.com',
    iosBundleId: 'com.example.urNextRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZOUAYjum-bLfwKv1YWnGfhs5jKSiRM0',
    appId: '1:1030067242876:ios:a5be6b0be35ac5ec3846f9',
    messagingSenderId: '1030067242876',
    projectId: 'ur-next-route',
    storageBucket: 'ur-next-route.appspot.com',
    iosBundleId: 'com.example.urNextRoute.RunnerTests',
  );
}
