name: Deploy and Restart Flask
on:
  workflow_dispatch:

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "py/"
          strip_components: 1
          target: "urnextroute"
      - name: Add in DB Credentials
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd urnextroute
            sed -i 's#mariadb+mariadbconnector://root@127.0.0.1:3306/urnextroute#mariadb+mariadbconnector://dbuser:${{ secrets.DB_PASSWORD }}@127.0.0.1:3306/urnextroute#g' db.py
      - name: Restart flask
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.PASSWORD }} | sudo -S systemctl restart urnextroute
        
